services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/app/.env

  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/.env
    depends_on:
      - db
  
  web:
    build: ./frontend
    command: node server/server.mjs
    ports:
      - "4000:4000"
    depends_on:
      - api

volumes:
  postgres_data:
